name: utube
version: '1'
summary: Download/Play Media from Youtube
description: |
  Utube is very powerful tool to download media files from various sites,
  Utube provide a unique interface which allow you manage your favourite videos and music from youtube.com
  You can download, play , save videos to your favourite list. Other features are -
  *play youtube
  *download youtube videos
  *download media in different formats, resolutions and qualities
  *search youtube
  *filter your search
  *Show speed , eta , size , progress , time added etc in download item and also saves it
  *have inbuild youtube player (No Flash, Native Player included)
  *download videos with one click 
  *Multiple downloads
  *full history support 
  *very fast no glitches
  You have to upgrade the application to pro for all features.
grade: stable
confinement: strict
icon: snap/gui/icon.png
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  utube:
    command: desktop-launch utube
    environment:
       QT_STYLE_OVERRIDE: "gtk"
       DISABLE_WAYLAND: 1
       QT_QPA_PLATFORMTHEME: gtk3 
    desktop: usr/share/applications/utube.desktop
    plugs:
        - home
        - unity7
        - browser-support
        - network
        - network-bind
        - opengl
        - pulseaudio
        - x11
        - alsa
        - desktop
        - network-manager
        - gsettings
        - process-control
        - desktop-legacy
        - wayland
        - mount-observe

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/usr/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/usr/share/sounds
    default-provider: gtk-common-themes
  qt551:
    interface: content
    target: $SNAP/qt551
    default-provider: qt551

parts:
   application:
     source-type: git
     source: https://github.com/keshavbhatt/ut.git
#     source: .
     plugin: qmake
     qt-version: qt5
     override-build: |
          snapcraftctl build
          sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/utube.desktop
          cp -rf ${SNAPCRAFT_PART_SRC}/utube.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/utube.desktop
     after: [desktop-qt5]

   snap-launcher:
     plugin: dump
     source: snap_launcher/
   desktop-qt5:
     plugin: nil
     build-packages:
       - build-essential
       - qtbase5-dev
       - dpkg-dev
       - libqt5webkit5-dev
   cleanup:
     after: [application]
     plugin: nil
     override-prime: |
         # Remove unneeded stage files to save space
         cd usr/share
         rm -rf apport bash-completion bug doc doc-base icons lintian man pam-configs pkgconfig themes upstart zsh
